---
language: ruby
rvm:
  - "1.9.2"
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode

matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: rbx-18mode
    - rvm: rbx-19mode
    - rvm: ruby-head

script:
  - cd spec/dummy
  - RAILS_ENV=test && bundle exec rake db:migrate
  - cd ../..
  - bundle exec rake
